### ISSUE TITLE
Oauth Twitter profile image resolution corrupted. 

### ISSUE THREAD

**Issue by baxcallan** [baxcallan/rails_junior_devs#51]
When pulling down the profile image from the Twitter API the resolution is corrupted  compare to the profile image from the Github API. 

The problem seems to be that the URL given by Twitter for the image is ```https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png``` . 
The ```_normal``` section in that URL seems to be corrupting the resolution for the profile image.
Because when the ```_normal``` is removed from the URL such as ```https://abs.twimg.com/sticky/default_profile_images/default_profile.png``` the image quality improves. 

Question is how to remove the ```_normal``` from the default URL form the Twitter API?

**Comment by CJbarbs** [comment]
You can use slice to remove the "_normal" from the returned image url from twitter. 

In `/app/models/user.rb`
```
  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
    user.update(
      username: auth_hash.info.nickname,
      image: auth_hash.info.image,
      token: auth_hash.credentials.token,
    )
```

Instead can be:

```
  def self.find_or_create_from_auth_hash(auth_hash)
    profile_image = auth_hash.info.image
    profile_image.slice! "_normal"
    user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
    user.update(
      username: auth_hash.info.nickname,
      image: profile_image,
      token: auth_hash.credentials.token,
    )
```

Which improves the picture quality.

**Comment by baxcallan** [comment]
Thanks Cam was a pleasure working with you.
